on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: get version from package
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          echo "VERSION=$(echo $version)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install

      - name: Install Dependencies
        run: yarn build

      - name: Install Dependencies
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: setup user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: patch version
        run: |
          yarn config set version-git-message "version %s"
          yarn version --patch
      - name: github
        run: |
          git add -A
          git push
