name: Build and Publish Release
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    name: Build and Publish Release
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   run: echo ${{ github.sha }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
      - name: Set Tag-Version
        env:
          TAG_VERSION: ${{ toJson(github.event.release.tag_name) }}
        run: |
          version=$(echo "$TAG_VERSION" | sed 's/v//')
          echo "VERSION=$(echo $version)" >> $GITHUB_ENV

      - name: Install Dependencies
        run: yarn install

      - name: build
        run: yarn build

      - name: login
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > ~/.npmrc

      - name: publish
        run: yarn publish --new-version ${{ env.VERSION }}
