on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: get version from package
        # env:
        #   GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          version=$(node -e "console.log(require('./package.json').version)")
          echo "VERSION=$(echo $version)" >> $GITHUB_ENV
        #   echo "$GITHUB_CONTEXT"
      - name: setup user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: patch version
        run: yarn version --patch
      - name: gut add
        run: git add -A
      - name: commit
        run: git commit -m "Update version ${{ env.VERSION }}"
      - name: status
        run: git status
      - name: push
        run: git push
